development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://artion.balliiballii.com:6379/1" } %>
  channel_prefix: artion_api_production
